name = "MITComputationalThinkingM1"
uuid = "c10c8566-6649-4ea4-b6c2-4a4465d50d00"
authors = ["Jędrzej Lewandowski <jedrzejblew@gmail.com>"]
version = "0.1.0"

[deps]
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
