name: "apply app using kubectl"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to katedra2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: false
      
      - name: Generate kubernetes config
        uses: actions/github-script@v5
        with:
          script: |
            const {makeK8ConfigFiles} = require("./k8/make-k8.js");
            makeK8ConfigFiles({ context });

      - name: "Prepare cert files"
        run: |
          echo "${K8_CLIENT_CERTIFICATE}" > "$HOME/k8_x509_cert.crt"
          echo "${K8_CLIENT_KEY}" > "$HOME/k8_x509_key.key"
        env:
          K8_CLIENT_CERTIFICATE: ${{ secrets.K8_CLIENT_CERTIFICATE }}
          K8_CLIENT_KEY: ${{ secrets.K8_CLIENT_KEY }}

      - name: Deploy to Kubernetes
        run: |
          kubectl \
            --server "${K8_SERVER}" --insecure-skip-tls-verify \
            --client-certificate "$HOME/k8_x509_cert.crt" \
            --client-key "$HOME/k8_x509_key.key" \
            apply \
            -f "${K8_CONFIG_DIR}" --namespace "${K8_NAMESPACE}"
        env:
          K8_SERVER: "https://katedra2.jblew.pl:16443"
          K8_NAMESPACE: medical-data-science
          K8_CONFIG_DIR: "k8/out"

