# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a all notebooks as Docker images to ghcr.io

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BASE: ${{ github.repository }}

jobs:
  identifynotebooks:
    runs-on: ubuntu-latest
    outputs:
      notebooks: ${{ steps.set-notebooks.outputs.notebooks }}
    steps:
      - uses: actions/checkout@v2
      - id: set-notebooks
        uses: actions/github-script@v5
        with:
          script: |
            const { getNotebookDirs, shouldBuild } = require(".github/workflows/utils.js")
            const notebookDirs = getNotebookDirs()
            const notebookDirsForBuilding = await notebookDirs.filter(
              async nbDir => {
                return await shouldBuild(nbDir, { github })
              }
            )
            const notebooksForBuildingNames = notebookDirsForBuilding.map(dir => dir.split("/").pop())
            const output = JSON.stringify(notebooksForBuildingNames)
            console.log(`'${output}'\n`)
            console.log(`::set-output name=notebooks::${output}`)
  
  build:
    runs-on: ubuntu-latest
    needs: [identifynotebooks]
    strategy:
      matrix:
        notebook: ${{fromJson(needs.identifynotebooks.outputs.notebooks)}}
      fail-fast: false
      max-parallel: 10
    steps:
      - run: echo "Building notebook ${{matrix.notebook}}"
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: gettags
        uses: actions/github-script@v5
        env:
          NOTEBOOK_NAME: ${{ matrix.notebook }}
        with:
          script: |
            const notebookName = process.env.NOTEBOOK_NAME
            const baseTag = `${context.repo.owner}/${context.repo.repo}-${notebookName.toLowerCase()}`
            const tags = [
              `${baseTag}:latest`
            ]
            console.log('Tags:', tags)
            console.log(`::set-output name=tags::${tags.join(".")}`)
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: "{{defaultContext}}:notebooks/${{ matrix.notebook }}"
          push: true
          tags: "${{ steps.gettags.outputs.tags }}"

  # build-and-push-image:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Log in to the Container registry
  #       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: ""

  #     - name: Extract metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
  #         tags: |
  #           type=ref,event=branch
  #           type=ref,event=pr
  #           type=semver,pattern={{version}}
  #           type=semver,pattern={{major}}.{{minor}}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
